# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_letter_words', models.CharField(max_length=10)),
                ('nine_letter_words', models.CharField(max_length=9)),
                ('eight_letter_words', models.CharField(max_length=8)),
                ('seven_letter_words', models.CharField(max_length=7)),
                ('six_letter_words', models.CharField(max_length=6)),
                ('five_letter_words', models.CharField(max_length=5)),
                ('four_letter_words', models.CharField(max_length=4)),
                ('three_letter_words', models.CharField(max_length=3)),
                ('two_letter_words', models.CharField(max_length=2)),
                ('one_letter_words', models.CharField(max_length=1)),
            ],
        ),
    ]
