# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Combination',
        ),
    ]
